# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/manger.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(886, 498)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 140, 58, 18))
        self.label.setObjectName("label")
        self.size = QtWidgets.QLineEdit(Form)
        self.size.setGeometry(QtCore.QRect(360, 130, 113, 32))
        self.size.setObjectName("size")
        self.error_message = QtWidgets.QLabel(Form)
        self.error_message.setGeometry(QtCore.QRect(30, 390, 771, 81))
        self.error_message.setText("")
        self.error_message.setObjectName("error_message")
        self.play_btn = QtWidgets.QPushButton(Form)
        self.play_btn.setGeometry(QtCore.QRect(380, 330, 90, 34))
        self.play_btn.setObjectName("play_btn")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(360, 190, 112, 26))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(360, 230, 112, 26))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 190, 81, 61))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Размер"))
        self.play_btn.setText(_translate("Form", "Играть"))
        self.radioButton.setText(_translate("Form", "Легкий"))
        self.radioButton_2.setText(_translate("Form", "Нормальный"))
        self.label_2.setText(_translate("Form", "Уровень \n"
"сложности"))
