# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/manger.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(708, 735)
        self.next_btn = QtWidgets.QPushButton(Form)
        self.next_btn.setGeometry(QtCore.QRect(300, 670, 90, 34))
        self.next_btn.setObjectName("next_btn")
        self.generate_new = QtWidgets.QPushButton(Form)
        self.generate_new.setGeometry(QtCore.QRect(170, 590, 141, 34))
        self.generate_new.setObjectName("generate_new")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 50, 681, 351))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.bl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.bl.setContentsMargins(0, 0, 0, 0)
        self.bl.setObjectName("bl")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.size_7 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.size_7.setObjectName("size_7")
        self.sizes = QtWidgets.QButtonGroup(Form)
        self.sizes.setObjectName("sizes")
        self.sizes.addButton(self.size_7)
        self.verticalLayout.addWidget(self.size_7)
        self.size_10 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.size_10.setObjectName("size_10")
        self.sizes.addButton(self.size_10)
        self.verticalLayout.addWidget(self.size_10)
        self.size_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.size_5.setChecked(True)
        self.size_5.setObjectName("size_5")
        self.sizes.addButton(self.size_5)
        self.verticalLayout.addWidget(self.size_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.easy_lvl = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.easy_lvl.setChecked(True)
        self.easy_lvl.setObjectName("easy_lvl")
        self.verticalLayout_2.addWidget(self.easy_lvl)
        self.normal_lvl = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.normal_lvl.setChecked(False)
        self.normal_lvl.setObjectName("normal_lvl")
        self.verticalLayout_2.addWidget(self.normal_lvl)
        self.hard_lvl = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.hard_lvl.setChecked(False)
        self.hard_lvl.setObjectName("hard_lvl")
        self.verticalLayout_2.addWidget(self.hard_lvl)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.bl.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.next_btn.setText(_translate("Form", "Далее"))
        self.generate_new.setText(_translate("Form", "Перегенерировать"))
        self.label.setText(_translate("Form", "Размер"))
        self.size_7.setText(_translate("Form", "7x7"))
        self.size_10.setText(_translate("Form", "10x10"))
        self.size_5.setText(_translate("Form", "5x5"))
        self.label_2.setText(_translate("Form", "Уровень \n"
"сложности"))
        self.easy_lvl.setText(_translate("Form", "Легкий"))
        self.normal_lvl.setText(_translate("Form", "Нормальный"))
        self.hard_lvl.setText(_translate("Form", "Сложный"))
