# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/start.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(807, 522)
        self.play_btn = QtWidgets.QPushButton(Dialog)
        self.play_btn.setGeometry(QtCore.QRect(350, 230, 90, 34))
        self.play_btn.setObjectName("play_btn")
        self.leader_btn = QtWidgets.QPushButton(Dialog)
        self.leader_btn.setGeometry(QtCore.QRect(340, 320, 121, 41))
        self.leader_btn.setObjectName("leader_btn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 70, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.play_btn.setText(_translate("Dialog", "Играть"))
        self.leader_btn.setText(_translate("Dialog", "Списки лидеров"))
        self.label.setText(_translate("Dialog", "Морской Бой"))
